[project]
name = "elt-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-postgres>=1.9.1",
    "python-dotenv>=1.0.0",
]
