[project]
name = "elt-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=46.0.3",
    "dbt-core>=1.10.15",
    "dbt-postgres>=1.9.1",
    "pandas>=2.3.3",
    "python-dotenv>=1.0.0",
]
